---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
type: Opaque
data:
  user: <user-id-hashed>
  password: <password-hashed>

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-uris
type: Opaque
data:
  db-connstr: <connection-string-hashed>

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <hash>

